### PR TITLE
18 sidebarmenu

### LINKED ISSUE #18: SideBarMenu
Create the SideBarMenu component to be able to display:
- User Info
- Wallet Key (?)
- Settings
- Theme toggle

**ISSUE**:
The Tab Navigation Menu from expo router is always on top of all the other components, tried applying a custom z-axis logic but did not work...

### PR DESCRIPTION
**Pull request by PaulThblt**
- Added Expo Drawer Navigation
- Expo lore-friendly side bar component with custom content and styling

### CODE REVIEW

File: app/(tabs)/index.tsx [hunk 1]
```diff
@@ -21,36 +20,33 @@ import '@ethersproject/shims';
 export default function Home() {
   const { isReady, user } = usePrivy();
 
-  useEffect(() => {
-    if (isReady && !user) {
-      router.navigate('login'); // TODO: disable login page back gesture
-    }
-  }, [isReady, user, router]);
+  // useEffect(() => {
```
Comment (bendsp) [inline app/(tabs)/index.tsx]: Do not disable login functionality in production

File: app/(tabs)/index.tsx [hunk 2]
```diff
@@ -21,36 +20,33 @@ import '@ethersproject/shims';
...
 
   if (!isReady) {
     return <Loading />;
   }
 
   //* Fail safe
-  if (!user) {
-    return null;
-  }
+  // if (!user) {
```
Comment (bendsp) [inline app/(tabs)/index.tsx]: same issue

**Review by bendsp — CHANGES_REQUESTED** [review]
fix commenting out the login functionality, then LGTM

**Review by bendsp — APPROVED** [review]

**Comment by bendsp** [comment]
lgtm
